name: Test

on: [pull_request]


jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    name: Testing Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install self
        run: pip install .

      - name: Lint with flake8
        run: flake8 .

      - name: Test with pytest
        run: pytest .
